name: Version Increment
description: Retries a shell command multiple times until success

outputs:
  new_tag:
    description: The new version tag

runs:
  using: composite
  steps:
    - name: Get the latest tag and increment patch version
      id: increment_version
      run: |
        git fetch --tags
        latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)

        if [ -z "$latest_tag" ]; then
          new_tag="v1.0.0"
        else
          major=$(echo $latest_tag | cut -d '.' -f 1 | sed 's/v//')
          minor=$(echo $latest_tag | cut -d '.' -f 2)
          patch=$(echo $latest_tag | cut -d '.' -f 3)
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
        fi

        echo "New version tag: $new_tag"
        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
