name: Version Increment
description: Retries a shell command multiple times until success
author: Segev Grotas

outputs:
  new_tag:
    description: The new version tag
    value: ${{ steps.increment.outputs.new_tag }}

runs:
  using: composite
  steps:
    - shell: bash
      id: increment
      run: |
        git fetch --tags

        current_tag=$(git tag --points-at HEAD | grep '^v' | sort -V | tail -n 1)
        if [ -n "$current_tag" ]; then
          new_tag="$current_tag"
          echo "Tag already exists on HEAD, using $current_tag"
        else
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)

          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            major=$(echo $latest_tag | cut -d '.' -f 1 | sed 's/v//')
            minor=$(echo $latest_tag | cut -d '.' -f 2)
            patch=$(echo $latest_tag | cut -d '.' -f 3)
            patch=$((patch + 1))
            new_tag="v${major}.${minor}.${patch}"
          fi

          echo "Generated new version tag: $new_tag"
        fi

        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
