name: entrytracker-ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  building_and_unit_testing:
    runs-on: ubuntu-latest
    name: Building and Unit Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run app
        run: python app.py &

      - name: Testing
        uses: ./.github/actions/retry
        with:
          command: curl -s http://localhost:5000/ | grep current_entry

      - name: Cleanup
        run: pkill -f "python app.py" || true

  packaging_e2e_testing_and_deploy:
    runs-on: ubuntu-latest
    name: Packaging E2E Testing and Deploy
    needs: building_and_unit_testing
    outputs:
      new_tag: ${{ steps.version.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Building
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: entrytracker:temp
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker Compose
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: docker compose up -d

      - name: Testing
        uses: ./.github/actions/retry
        with:
          command: curl -s http://localhost:80/ | grep previous_entries

      - name: Cleanup
        run: docker compose down

      - name: Fetch tag
        id: version
        uses: ./.github/actions/version-increment

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run push command
        env:
          TAG: ${{steps.version.outputs.new_tag}}
        run: |
          docker tag entrytracker:temp ${{ secrets.ECR_URL }}:$TAG
          docker push ${{ secrets.ECR_URL }}:$TAG

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: packaging_e2e_testing_and_deploy
    env:
      Tag: ${{ needs.packaging_e2e_testing_and_deploy.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload docker compose to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "compose.yaml"
          target: "~"

      - name: Connection with ssh to ec2
        uses: appleboy/ssh-action@v1.0.0
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DB_HOST,DB_USER,DB_PASSWORD,DB_NAME
          script: |
            sudo apt-get update -y

            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi

            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -o awscliv2.zip
              sudo ./aws/install
            fi

            if ! command -v curl &> /dev/null; then
              sudo apt-get install -y curl
            fi

            if ! docker compose version &> /dev/null; then
              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              mkdir -p $DOCKER_CONFIG/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 \
                -o $DOCKER_CONFIG/cli-plugins/docker-compose
              chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            fi

            docker --version
            docker compose version
            aws --version
            curl --version

            aws ecr get-login-password --region ap-south-1 \
              | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

            sed -i "s|entrytracker:temp|${{ secrets.ECR_URL }}:${{ env.Tag }}|g" ~/compose.yaml
            sed -i '/^[[:space:]]*build:/,/^[[:space:]]*[^[:space:]]/ { /^[[:space:]]*build:/d; /^[[:space:]]*context:/d }' ~/compose.yaml

            if docker network inspect entryTracker-network >/dev/null 2>&1; then
              sed -i '/entryTracker-network:/,/^[[:space:]]*[^[:space:]]/c\  entryTracker-network:\n    external: true' ~/compose.yaml
            fi

            docker compose -f ~/compose.yaml up -d

      # - name: Push new version to github
      #   run: |
      #     git tag $TAG
      #     git push origin $TAG

  # Report -> email/slack
